config/routes.rb
Rails.application.routes.draw do
  
  root 'links#index'

  resources :links do
        get :shortened, on: :collection
   end

   get ':format' => 'links#shortened'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
require 'open-uri'
class Link < ApplicationRecord

	has_many :stats

	UNIQUE_ID_LENGTH = 6.freeze
	before_validation :smart_add_url_protocol
	validates :original_url, presence: true, on: :create, :format => URI::regexp(%w(http https))
	validates :original_url, uniqueness: true
	before_create :generate_short_url
	before_create :censor


	def generate_short_url
		url = ([*('a'..'z'), *('0'..'9')]).sample(UNIQUE_ID_LENGTH).join
		old_url = Link.where(short_url: url).last
		if old_url.present?
		  self.generate_short_url
		else
		  self.short_url = url
		end
	end

	def find_duplicate
	  Link.find_by_censor_url(self.censor_url)
	end

	def new_url?
	  find_duplicate.nil?
	end

	def censor
	  self.original_url.strip!
	  self.censor_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
	  self.censor_url = "http://#{self.censor_url}" 
	end


	private

	def smart_add_url_protocol
	  unless self.original_url[/\Ahttp:\/\//] || self.original_url[/\Ahttps:\/\//]
	    self.original_url = "http://#{self.original_url}"
	  end
	end
end

app/models/stat.rb
class Stat < ApplicationRecord
	belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

 
  def index
    @host = request.host_with_port
    @links = Link.all
  end


  def show

  end

  
  def new
    @link = Link.new
  end

  
  def edit
  end

  def create
    @link = Link.new(link_params)
    @link.original_url = link_params[:original_url]
    @link.censor
    if @link.new_url?
      respond_to do |format|
        if @link.save
          format.html { redirect_to root_path, notice: 'Link was successfully created.' }
          format.json { render :index, status: :created, location: @link }
        else
          format.html { render :new }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:notice] = "A Tiny Url for this Link alredy exists.🙃"
      redirect_to new_link_path
    end

  end


  def shortened
    url = Link.find_by_short_url(params[:format])
    if url.present?
      counter = url.clicks + 1
      url.update_attributes(:clicks => counter)
      url.stats.create(platform: browser.platform.to_s, ip_address: request.remote_ip.to_s)
      redirect_to url.original_url
    else
      flash[:notice] = "URL Cannot be Found"
      redirect_to root_path
    end
  end


  def update
    @link.original_url = link_params[:original_url]
    @link.censor
      respond_to do |format|
        if @link.update_attributes(original_url: link_params[:original_url])
          format.html { redirect_to root_path, notice: 'Link was successfully updated.' }
          format.json { render :index, status: :created, location: @link }
        else
          format.html { render :new }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_link
      @link = Link.find(params[:id])
    end

   
    def link_params
      params.require(:link).permit(:original_url, :short_url, :censor_url, :clicks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def base_url(short_url = nil)
    "#{request.protocol}#{request.host_with_port}/#{short_url}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrl</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>

  <style>
  .container{
  	text-align: center!important;
  }
  .funny-btn{
    font-size: xx-large;
    text-decoration: none;
  }
</style>

</html>

app/views/links/_form.html.erb
<%= form_for(link, html: {class: "form-horizontal"}) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2> Enter the url to be shortned: </h2>
    <%= f.text_field :original_url, class: 'inpput-large'%>
  </div><br>

  <div class="actions">
    <%= f.submit "Hit Me Up", :class => "btn btn-success" %><br>
  </div><br>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>BIGGER is NOT Always Better...</h1>
<h2>So Lets Make your URL Tiny..</h2>

<br>

<%= link_to 'Lets Get you One😄', new_link_path, class: "funny-btn" %>



<br><br><br>
<h2> People Prefer smaller Size, These days 😋</h2>
<h3>Dont Believe us have a Look Below then 🤨</h3><br><br><br>
<table class="table table-condensed">
  <thead>
    <tr>
      <th class="table-text">Original url</th>
      <th class="table-text">Shortened url</th>
      <th class="table-text">Times Visited</th>
      <th class="table-text" colspan="3">Actions Available</th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.original_url %></td>
        <td><%= link_to "#{base_url(link.short_url)}", shortened_links_path(link.short_url), target: "_blank"  %></td>
        <td><%= link.clicks %></td>
        <td><%= link_to 'show stats', link_path(link) %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<style>
  .table-text{
    text-align: center;
  }
</style>

app/views/links/new.html.erb
<h1>Lets Make your URL Short</h1>

<div id="notice"><%= notice %></div>

<%= render 'form', link: @link %>

<%= button_to 'Please, Dont Leave Me😞', {:controller => "links", :action => "index", :link => @link,} , :method=>:get , class: "funny-btn" %>

app/views/links/show.html.erb
<table class="table table-hover">
    <thead>
      <tr>
      	<th class="table-text">S.No</th>
        <th class="table-text">Original Link</th>
        <th class="table-text">Short URL</th>
        <th class="table-text">Platform</th>
        <th class="table-text">Client IP</th>
      </tr>
    </thead>
    <tbody>
    <% @link.stats.each_with_index do|stat,index| %>
      <tr>
      	<td><%= index + 1 %></td>
        <td><%= @link.original_url %></td>
        <td><%= "#{base_url(@link.short_url)}" %></td>
        <td><%= stat.platform %></td>
        <td><%= stat.ip_address %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<%= button_to 'Lets Take you Back 😊', {:controller => "links", :action => "index", :link => @link,} , :method=>:get , class: "funny-btn" %>


  <style>
  .table-text{
    text-align: center;
  }
</style>